2012/03/06 11:43:53 [error] [exception.com_exception] exception 'com_exception' with message '<b>Source:</b> Unknown<br/><b>Description:</b> Unknown' in C:\xampp\htdocs\work\data-aggregration\protected\components\DaTool.php:69
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\protected\components\DaTool.php(69): com->Run('C:\xampp\htdocs...', 0, false)
#1 C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php(64): DaTool::exec('C:\xampp\htdocs...')
#2 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): ImportSiteHistoryController->actionImport()
#3 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\work\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\work\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): CController->run('import')
#7 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('importsitehisto...')
#8 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#9 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/work/data-aggregration/index.php/importsitehistory/import?siteconfig_id=2
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/site
---
2012/03/07 03:44:36 [error] [php] Undefined variable: siteconfig (C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php:24)
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CController.php(287): ImportSiteHistoryController->runAction()
#1 C:\xampp\htdocs\work\framework\web\CController.php(266): ImportSiteHistoryController->runActionWithFilters()
#2 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): ImportSiteHistoryController->run()
#3 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/work/data-aggregration/index.php/importsitehistory/index
2012/03/07 07:03:49 [error] [php] Object of class ImportSiteHistoryController could not be converted to string (C:\xampp\htdocs\work\data-aggregration\protected\views\importsitehistory\site.php:31)
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CController.php(870): ImportSiteHistoryController->renderFile()
#1 C:\xampp\htdocs\work\framework\web\CController.php(783): ImportSiteHistoryController->renderPartial()
#2 C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php(39): ImportSiteHistoryController->render()
#3 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): ImportSiteHistoryController->actionSite()
#4 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\work\framework\web\CController.php(287): ImportSiteHistoryController->runAction()
#6 C:\xampp\htdocs\work\framework\web\CController.php(266): ImportSiteHistoryController->runActionWithFilters()
#7 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): ImportSiteHistoryController->run()
#8 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#9 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/work/data-aggregration/index.php/importsitehistory/site
2012/03/07 07:05:23 [error] [php] Object of class ImportSiteHistoryController could not be converted to string (C:\xampp\htdocs\work\data-aggregration\protected\views\siteconfig\_detail.php:15)
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CController.php(870): ImportSiteHistoryController->renderFile()
#1 C:\xampp\htdocs\work\data-aggregration\protected\views\importsitehistory\index.php(9): ImportSiteHistoryController->renderPartial()
#2 C:\xampp\htdocs\work\framework\web\CBaseController.php(127): require()
#3 C:\xampp\htdocs\work\framework\web\CBaseController.php(96): ImportSiteHistoryController->renderInternal()
#4 C:\xampp\htdocs\work\framework\web\CController.php(870): ImportSiteHistoryController->renderFile()
#5 C:\xampp\htdocs\work\framework\web\CController.php(783): ImportSiteHistoryController->renderPartial()
#6 C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php(25): ImportSiteHistoryController->render()
#7 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): ImportSiteHistoryController->actionIndex()
#8 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams()
#9 C:\xampp\htdocs\work\framework\web\CController.php(287): ImportSiteHistoryController->runAction()
#10 C:\xampp\htdocs\work\framework\web\CController.php(266): ImportSiteHistoryController->runActionWithFilters()
#11 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): ImportSiteHistoryController->run()
#12 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#13 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=2
2012/03/07 07:54:37 [error] [php] Undefined index: siteconfig_id (C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php:10)
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CController.php(287): ImportSiteHistoryController->runAction()
#1 C:\xampp\htdocs\work\framework\web\CController.php(266): ImportSiteHistoryController->runActionWithFilters()
#2 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): ImportSiteHistoryController->run()
#3 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/work/data-aggregration/index.php/importsitehistory
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php (10)
in C:\xampp\htdocs\work\data-aggregration\index.php (13)
2012/03/07 07:54:37 [error] [php] Undefined index: siteconfig_id (C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php:10)
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CController.php(287): ImportSiteHistoryController->runAction()
#1 C:\xampp\htdocs\work\framework\web\CController.php(266): ImportSiteHistoryController->runActionWithFilters()
#2 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): ImportSiteHistoryController->run()
#3 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/work/data-aggregration/index.php/importsitehistory
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php (10)
in C:\xampp\htdocs\work\data-aggregration\index.php (13)
2012/03/12 10:13:06 [error] [php] require_once(C:\xampp\htdocs\work\data-aggregration\DJJobConfig.php) [<a href='function.require-once'>function.require-once</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\work\data-aggregration\jobrunner.php:10)
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(10): CWebApplication->handleError()
#1 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(10): require_once()
REQUEST_URI=/work/data-aggregration/jobrunner.php
2012/03/12 10:17:09 [error] [php] require_once(C:\xampp\htdocs\work\data-aggregration\DJJobConfig.php) [<a href='function.require-once'>function.require-once</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\work\data-aggregration\jobrunner.php:10)
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(10): CWebApplication->handleError()
#1 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(10): require_once()
REQUEST_URI=/work/data-aggregration/jobrunner.php
2012/03/12 10:17:11 [error] [php] require_once(C:\xampp\htdocs\work\data-aggregration\DJJobConfig.php) [<a href='function.require-once'>function.require-once</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\work\data-aggregration\jobrunner.php:10)
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(10): CWebApplication->handleError()
#1 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(10): require_once()
REQUEST_URI=/work/data-aggregration/jobrunner.php
2012/03/12 10:17:14 [error] [php] require_once(C:\xampp\htdocs\work\data-aggregration\DJJobConfig.php) [<a href='function.require-once'>function.require-once</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\work\data-aggregration\jobrunner.php:10)
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(10): CWebApplication->handleError()
#1 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(10): require_once()
REQUEST_URI=/work/data-aggregration/jobrunner.php
2012/03/12 10:17:15 [error] [php] require_once(C:\xampp\htdocs\work\data-aggregration\DJJobConfig.php) [<a href='function.require-once'>function.require-once</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\work\data-aggregration\jobrunner.php:10)
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(10): CWebApplication->handleError()
#1 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(10): require_once()
REQUEST_URI=/work/data-aggregration/jobrunner.php
2012/03/12 10:17:15 [error] [php] require_once(C:\xampp\htdocs\work\data-aggregration\DJJobConfig.php) [<a href='function.require-once'>function.require-once</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\work\data-aggregration\jobrunner.php:10)
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(10): CWebApplication->handleError()
#1 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(10): require_once()
REQUEST_URI=/work/data-aggregration/jobrunner.php
2012/03/12 10:17:16 [error] [php] require_once(C:\xampp\htdocs\work\data-aggregration\DJJobConfig.php) [<a href='function.require-once'>function.require-once</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\work\data-aggregration\jobrunner.php:10)
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(10): CWebApplication->handleError()
#1 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(10): require_once()
REQUEST_URI=/work/data-aggregration/jobrunner.php
2012/03/12 10:17:18 [error] [php] require_once(C:\xampp\htdocs\work\data-aggregration\DJJobConfig.php) [<a href='function.require-once'>function.require-once</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\work\data-aggregration\jobrunner.php:10)
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(10): CWebApplication->handleError()
#1 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(10): require_once()
REQUEST_URI=/work/data-aggregration/jobrunner.php
2012/03/12 10:17:20 [error] [php] require_once(C:\xampp\htdocs\work\data-aggregration\DJJobConfig.php) [<a href='function.require-once'>function.require-once</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\work\data-aggregration\jobrunner.php:10)
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(10): CWebApplication->handleError()
#1 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(10): require_once()
REQUEST_URI=/work/data-aggregration/jobrunner.php
2012/03/12 10:19:05 [error] [php] include(DJWorker.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\work\framework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(14): spl_autoload_call()
REQUEST_URI=/work/data-aggregration/jobrunner.php
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (14)
2012/03/12 10:46:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/2?_=1331545560129
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=2
---
2012/03/12 11:14:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/2?_=1331547283528
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=2
---
2012/03/12 12:01:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331550104966
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/13 05:03:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/2?_=1331611381208
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=2
---
2012/03/13 05:36:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/2?_=1331613385448
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=2
---
2012/03/13 07:03:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "data-aggregration/jobrunner.php".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('data-aggregrati...')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/data-aggregration/jobrunner.php?XDEBUG_SESSION_START=netbeans-xdebug
---
2012/03/13 08:14:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/2?_=1331622889712
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=2
---
2012/03/13 08:17:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/2?_=1331623069855
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=2
---
2012/03/13 08:17:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331623077125
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/13 08:19:46 [error] [system.db.CDbCommand] CDbCommand::() failed: SQLSTATE[42S02]: [Microsoft][SQL Server Native Client 10.0][SQL Server]Invalid object name 'tblcvtbdrugs'.. The SQL statement executed was:  SELECT * FROM tblcvtbdrugs.
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (201)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (146)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (100)
2012/03/13 08:19:48 [error] [php] Invalid argument supplied for foreach() (C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php:144)
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJob.php(244): DaImportSiteJob->perform()
#1 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJob.php(212): DJJob->run()
#2 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(21): DJWorker->start()

in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (144)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (100)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImportSiteJob.php (11)
2012/03/13 08:30:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331623847970
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/13 08:31:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331623894091
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/13 08:31:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/2?_=1331623899963
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=2
---
2012/03/13 08:33:27 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1901' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO tblclinic (clinic,  clinickh,  art,  district,  od,  province) VALUES (:clinic, :clinickh, :art, :district, :od, :province).
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (225)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (146)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (100)
2012/03/13 08:33:27 [error] [application] handling
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaTool.php (15)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (228)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (146)
2012/03/13 08:33:27 [error] [application] invalid clicnic handling
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaTool.php (15)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (231)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (146)
2012/03/13 08:33:27 [error] [application] CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1901' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO tblclinic (clinic,  clinickh,  art,  district,  od,  province) VALUES (:clinic, :clinickh, :art, :district, :od, :province)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaTool.php (15)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (153)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (100)
2012/03/13 08:33:27 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '000001-0002' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO tblaimain (clinicid,  datefirstvisit,  age,  sex,  house,  street,  grou,  village,  commune,  district,  province,  phone,  namecontps1,  contaddress1,  contphone1,  namecontps2,  contaddress2,  contphone2,  maritalstatus,  occupation,  education,  rea,  writ,  referredfrom,  namelocationhbc,  dateconfposhiv,  datelastneghiv,  offyesno,  offtransferin,  datestaart,  artnumber,  tbpasmedihis,  gravida,  para,  dailyalcohol,  tabacco,  idu,  yama,  previousarv,  precontrimoxazole,  prefluconzazole,  preisoniazid,  pretranditional,  drugallergy,  vct,  pclinicid,  id) VALUES (:clinicid, :datefirstvisit, :age, :sex, :house, :street, :grou, :village, :commune, :district, :province, :phone, :namecontps1, :contaddress1, :contphone1, :namecontps2, :contaddress2, :contphone2, :maritalstatus, :occupation, :education, :rea, :writ, :referredfrom, :namelocationhbc, :dateconfposhiv, :datelastneghiv, :offyesno, :offtransferin, :datestaart, :artnumber, :tbpasmedihis, :gravida, :para, :dailyalcohol, :tabacco, :idu, :yama, :previousarv, :precontrimoxazole, :prefluconzazole, :preisoniazid, :pretranditional, :drugallergy, :vct, :pclinicid, :id).
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (225)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (146)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (100)
2012/03/13 08:33:27 [error] [application] handling
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaTool.php (15)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (228)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (146)
2012/03/13 08:33:27 [error] [application] keep throwing handling
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaTool.php (15)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (235)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (146)
2012/03/13 08:33:28 [error] [php] Invalid argument supplied for foreach() (C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php:144)
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJob.php(244): DaImportSiteJob->perform()
#1 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJob.php(212): DJJob->run()
#2 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(21): DJWorker->start()

in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (144)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (100)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImportSiteJob.php (11)
2012/03/13 08:52:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331625121106
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/13 08:52:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/2?_=1331625126749
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=2
---
2012/03/13 08:54:34 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1901' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO tblclinic (clinic,  clinickh,  art,  district,  od,  province) VALUES (:clinic, :clinickh, :art, :district, :od, :province).
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (225)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (146)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (100)
2012/03/13 08:54:34 [error] [application] handling
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaTool.php (15)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (228)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (146)
2012/03/13 08:54:34 [error] [application] invalid clicnic handling
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaTool.php (15)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (231)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (146)
2012/03/13 08:54:34 [error] [application] CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1901' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO tblclinic (clinic,  clinickh,  art,  district,  od,  province) VALUES (:clinic, :clinickh, :art, :district, :od, :province)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaTool.php (15)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (153)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (100)
2012/03/13 08:55:58 [error] [php] Invalid argument supplied for foreach() (C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php:144)
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJob.php(244): DaImportSiteJob->perform()
#1 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJob.php(212): DJJob->run()
#2 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(20): DJWorker->start()

in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (144)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (100)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImportSiteJob.php (11)
2012/03/13 09:31:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331627474971
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/13 09:31:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/2?_=1331627481456
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=2
---
2012/03/13 09:34:27 [error] [system.db.CDbCommand] CDbCommand::() failed: SQLSTATE[42S02]: [Microsoft][SQL Server Native Client 10.0][SQL Server]Invalid object name 'tblcvtbdrugs'.. The SQL statement executed was:  SELECT * FROM tblcvtbdrugs.
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (203)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (149)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (100)
2012/03/13 09:34:29 [error] [php] Invalid argument supplied for foreach() (C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php:147)
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJob.php(244): DaImportSiteJob->perform()
#1 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJob.php(212): DJJob->run()
#2 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(20): DJWorker->start()

in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (147)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (100)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImportSiteJob.php (11)
2012/03/13 09:52:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331628722299
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/13 09:54:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331628842474
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/13 10:01:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331629281219
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/13 10:03:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331629403877
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/13 10:03:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/2?_=1331629410534
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=2
---
2012/03/13 10:05:05 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1901' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO tblclinic (clinic,  clinickh,  art,  district,  od,  province) VALUES (:clinic, :clinickh, :art, :district, :od, :province).
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (223)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (147)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (100)
2012/03/13 10:05:05 [error] [application] handling
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaTool.php (15)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (226)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (147)
2012/03/13 10:05:05 [error] [application] invalid clicnic handling
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaTool.php (15)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (229)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (147)
2012/03/13 10:05:05 [error] [application] CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1901' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO tblclinic (clinic,  clinickh,  art,  district,  od,  province) VALUES (:clinic, :clinickh, :art, :district, :od, :province)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaTool.php (15)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (154)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (100)
2012/03/13 10:06:22 [error] [php] Invalid argument supplied for foreach() (C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php:145)
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJob.php(244): DaImportSiteJob->perform()
#1 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJob.php(212): DJJob->run()
#2 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(20): DJWorker->start()

in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (145)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (100)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImportSiteJob.php (11)
2012/03/13 10:12:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331629937131
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/13 10:12:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/2?_=1331629941716
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=2
---
2012/03/14 09:38:55 [error] [php] Undefined variable: code (C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php:33)
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CController.php(287): ImportSiteHistoryController->runAction()
#1 C:\xampp\htdocs\work\framework\web\CController.php(266): ImportSiteHistoryController->runActionWithFilters()
#2 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): ImportSiteHistoryController->run()
#3 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/work/data-aggregration/index.php/importsitehistory/site
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php (33)
in C:\xampp\htdocs\work\data-aggregration\index.php (13)
2012/03/14 09:39:10 [error] [exception.DaInvalidSiteException] exception 'DaInvalidSiteException' with message 'Invalid site code : 0002' in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php:255
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php(275): DaImporter->_getSiteConfig('0002')
#1 C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php(33): DaImporter->_getDbX('0002')
#2 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): ImportSiteHistoryController->actionSite()
#3 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\work\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\work\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): CController->run('site')
#7 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('importsitehisto...')
#8 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#9 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/work/data-aggregration/index.php/importsitehistory/site
---
2012/03/14 09:39:33 [error] [exception.DaInvalidSiteException] exception 'DaInvalidSiteException' with message 'Invalid site code : 0002' in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php:255
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php(275): DaImporter->_getSiteConfig('0002')
#1 C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php(33): DaImporter->_getDbX('0002')
#2 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): ImportSiteHistoryController->actionSite()
#3 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\work\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\work\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): CController->run('site')
#7 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('importsitehisto...')
#8 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#9 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/work/data-aggregration/index.php/importsitehistory/site
---
2012/03/14 09:42:26 [error] [exception.DaInvalidSiteException] exception 'DaInvalidSiteException' with message 'Invalid site code : 00020' in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php:255
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php(275): DaImporter->_getSiteConfig('00020')
#1 C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php(33): DaImporter->_getDbX('00020')
#2 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): ImportSiteHistoryController->actionSite()
#3 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\work\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\work\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): CController->run('site')
#7 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('importsitehisto...')
#8 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#9 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/work/data-aggregration/index.php/importsitehistory/site
---
2012/03/14 09:54:19 [error] [system.db.CDbCommand] CDbCommand::fetch() failed: SQLSTATE[IMSSP]: Tried to bind parameter number -1.  SQL Server supports a maximum of 2100 parameters.. The SQL statement executed was: SELECT ART FROM tblclinic.
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php (293)
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php (33)
in C:\xampp\htdocs\work\data-aggregration\index.php (13)
2012/03/14 09:54:19 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[IMSSP]: Tried to bind parameter number -1.  SQL Server supports a maximum of 2100 parameters.. The SQL statement executed was: SELECT ART FROM tblclinic' in C:\xampp\htdocs\work\framework\db\CDbCommand.php:528
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbCommand.php(408): CDbCommand->queryInternal('fetch', Array, Array)
#1 C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php(293): CDbCommand->queryRow()
#2 C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php(33): DaImporter->_getDbX('0002')
#3 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): ImportSiteHistoryController->actionSite()
#4 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\work\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\work\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): CController->run('site')
#8 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('importsitehisto...')
#9 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/work/data-aggregration/index.php/importsitehistory/site
---
2012/03/14 09:56:59 [error] [exception.DaInvalidSiteDatabaseException] exception 'DaInvalidSiteDatabaseException' with message 'Invalid site code: 0002 with ART code: 0001         ' in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php:297
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php(33): DaImporter->_getDbX('0002')
#1 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): ImportSiteHistoryController->actionSite()
#2 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\work\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\work\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): CController->run('site')
#6 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('importsitehisto...')
#7 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#8 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/work/data-aggregration/index.php/importsitehistory/site
---
2012/03/14 09:58:44 [error] [exception.DaInvalidSiteDatabaseException] exception 'DaInvalidSiteDatabaseException' with message 'Invalid site code: 0002 with ART code: 0001         
         
 You must make them the same value. By change site code to : 0001        
        ' in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php:297
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php(33): DaImporter->_getDbX('0002')
#1 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): ImportSiteHistoryController->actionSite()
#2 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\work\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\work\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): CController->run('site')
#6 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('importsitehisto...')
#7 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#8 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/work/data-aggregration/index.php/importsitehistory/site
---
2012/03/14 09:59:12 [error] [exception.DaInvalidSiteDatabaseException] exception 'DaInvalidSiteDatabaseException' with message 'Invalid site code: 0002 with ART code: 0001         
         
 You must make them the same values by change site code to : 0001        
        ' in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImporter.php:297
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php(33): DaImporter->_getDbX('0002')
#1 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): ImportSiteHistoryController->actionSite()
#2 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\work\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\work\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): CController->run('site')
#6 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('importsitehisto...')
#7 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#8 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/work/data-aggregration/index.php/importsitehistory/site
---
2012/03/15 10:16:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331802995511
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/15 10:17:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331803078606
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/15 10:20:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331803251748
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/15 10:23:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331803393372
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/15 10:24:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331803444801
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/15 10:24:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331803460267
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/15 10:25:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331803529285
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/15 10:28:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331803699648
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/15 10:28:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331803719650
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/15 10:30:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331803814812
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/15 10:33:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331804014572
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/15 10:33:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331804021310
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/15 10:45:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331804743794
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/15 10:50:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331805017330
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/15 11:06:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331805989941
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/15 11:13:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331806389312
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/15 11:13:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331806396232
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/15 11:13:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331806422506
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/15 11:34:04 [error] [exception.CHttpException.Import history with id: 16 not found] exception 'CHttpException' in C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php:37
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): ImportSiteHistoryController->actionDelete()
#1 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#2 C:\xampp\htdocs\work\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#3 C:\xampp\htdocs\work\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): CController->run('delete')
#5 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('importsitehisto...')
#6 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#7 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/work/data-aggregration/index.php/importsitehistory/delete/16
---
2012/03/15 11:34:10 [error] [exception.CHttpException.Import history with id: 16 not found] exception 'CHttpException' in C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php:37
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): ImportSiteHistoryController->actionDelete()
#1 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#2 C:\xampp\htdocs\work\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#3 C:\xampp\htdocs\work\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): CController->run('delete')
#5 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('importsitehisto...')
#6 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#7 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/work/data-aggregration/index.php/importsitehistory/delete/16
---
2012/03/15 11:34:15 [error] [exception.CHttpException.Import history with id: 16 not found] exception 'CHttpException' in C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php:37
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): ImportSiteHistoryController->actionDelete()
#1 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#2 C:\xampp\htdocs\work\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#3 C:\xampp\htdocs\work\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): CController->run('delete')
#5 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('importsitehisto...')
#6 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#7 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/work/data-aggregration/index.php/importsitehistory/delete/16
---
2012/03/15 15:05:17 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\work\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CApplication.php(431): CModule->getComponent('db')
#4 C:\xampp\htdocs\work\framework\db\ar\CActiveRecord.php(615): CApplication->getDb()
#5 C:\xampp\htdocs\work\framework\db\ar\CActiveRecord.php(2263): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\work\framework\db\ar\CActiveRecord.php(379): CActiveRecordMetaData->__construct(Object(User))
#7 C:\xampp\htdocs\work\data-aggregration\protected\models\User.php(34): CActiveRecord::model('User')
#8 C:\xampp\htdocs\work\data-aggregration\protected\components\UserIdentity.php(21): User::model()
#9 C:\xampp\htdocs\work\data-aggregration\protected\models\LoginForm.php(49): UserIdentity->authenticate()
#10 C:\xampp\htdocs\work\framework\validators\CInlineValidator.php(43): LoginForm->authenticate('password', Array)
#11 C:\xampp\htdocs\work\framework\validators\CValidator.php(197): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 C:\xampp\htdocs\work\framework\base\CModel.php(158): CValidator->validate(Object(LoginForm), NULL)
#13 C:\xampp\htdocs\work\data-aggregration\protected\controllers\UserController.php(21): CModel->validate()
#14 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): UserController->actionLogin()
#15 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\work\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\work\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): CController->run('login')
#19 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('user/login')
#20 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#21 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/work/data-aggregration/index.php/login
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/login
---
2012/03/15 15:07:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "id/view".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('id/view')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/id/1?_=1331820453785
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=1
---
2012/03/15 15:11:55 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\work\data-aggregration\protected\views\importsitehistory\index.php:19)
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CController.php(870): ImportSiteHistoryController->renderFile()
#1 C:\xampp\htdocs\work\framework\web\CController.php(783): ImportSiteHistoryController->renderPartial()
#2 C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php(26): ImportSiteHistoryController->render()
#3 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): ImportSiteHistoryController->actionIndex()
#4 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\work\framework\web\CController.php(287): ImportSiteHistoryController->runAction()
#6 C:\xampp\htdocs\work\framework\web\CController.php(266): ImportSiteHistoryController->runActionWithFilters()
#7 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): ImportSiteHistoryController->run()
#8 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#9 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/work/data-aggregration/index.php/importsitehistory
in C:\xampp\htdocs\work\data-aggregration\protected\views\importsitehistory\index.php (19)
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php (26)
in C:\xampp\htdocs\work\data-aggregration\index.php (13)
2012/03/16 05:17:56 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`server_oi_dev`.`da_backups`, CONSTRAINT `fk_da_bakups_siteconfig_id` FOREIGN KEY (`siteconfig_id`) REFERENCES `da_siteconfigs` (`id`)). The SQL statement executed was: DELETE FROM `da_siteconfigs` WHERE `da_siteconfigs`.`id`=1.
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\SiteConfigController.php (39)
in C:\xampp\htdocs\work\data-aggregration\index.php (13)
2012/03/16 05:18:34 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`server_oi_dev`.`da_backups`, CONSTRAINT `fk_da_bakups_siteconfig_id` FOREIGN KEY (`siteconfig_id`) REFERENCES `da_siteconfigs` (`id`)). The SQL statement executed was: DELETE FROM `da_siteconfigs` WHERE `da_siteconfigs`.`id`=1.
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\SiteConfigController.php (39)
in C:\xampp\htdocs\work\data-aggregration\index.php (13)
2012/03/16 05:24:39 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`server_oi_dev`.`da_import_site_histories`, CONSTRAINT `fk_da_import_site_histories_siteconfig_id` FOREIGN KEY (`siteconfig_id`) REFERENCES `da_siteconfigs` (`id`)). The SQL statement executed was: DELETE FROM `da_siteconfigs` WHERE `da_siteconfigs`.`id`=1.
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\SiteConfigController.php (39)
in C:\xampp\htdocs\work\data-aggregration\index.php (13)
2012/03/16 08:51:32 [error] [php] Array to string conversion (C:\xampp\htdocs\work\data-aggregration\protected\models\DaDbConnection.php:21)
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\protected\controllers\SiteConfigController.php(76): DaDbConnection->connect()
#1 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): SiteConfigController->actionTestConnection()
#2 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\work\framework\web\CController.php(287): SiteConfigController->runAction()
#4 C:\xampp\htdocs\work\framework\web\CController.php(266): SiteConfigController->runActionWithFilters()
#5 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): SiteConfigController->run()
#6 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#7 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#8 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/siteconfig/testConnection?SiteConfig[code]=0001&SiteConfig[name]=Battambong&SiteConfig[host]=localhost&SiteConfig[db]=site_new_oi&SiteConfig[user]=saj&SiteConfig[password]=123456&_=1331884216094
in C:\xampp\htdocs\work\data-aggregration\protected\models\DaDbConnection.php (21)
in C:\xampp\htdocs\work\data-aggregration\protected\models\DaDbConnection.php (11)
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\SiteConfigController.php (76)
2012/03/16 08:52:56 [error] [php] Array to string conversion (C:\xampp\htdocs\work\data-aggregration\protected\models\DaDbConnection.php:22)
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\protected\controllers\SiteConfigController.php(76): DaDbConnection->connect()
#1 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): SiteConfigController->actionTestConnection()
#2 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\work\framework\web\CController.php(287): SiteConfigController->runAction()
#4 C:\xampp\htdocs\work\framework\web\CController.php(266): SiteConfigController->runActionWithFilters()
#5 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): SiteConfigController->run()
#6 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#7 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#8 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/siteconfig/testConnection?SiteConfig[code]=0001&SiteConfig[name]=Battambong&SiteConfig[host]=localhost&SiteConfig[db]=site_new_oi&SiteConfig[user]=saj&SiteConfig[password]=123456&_=1331884216094
in C:\xampp\htdocs\work\data-aggregration\protected\models\DaDbConnection.php (22)
in C:\xampp\htdocs\work\data-aggregration\protected\models\DaDbConnection.php (11)
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\SiteConfigController.php (76)
2012/03/16 08:53:00 [error] [php] Array to string conversion (C:\xampp\htdocs\work\data-aggregration\protected\models\DaDbConnection.php:22)
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\protected\controllers\SiteConfigController.php(76): DaDbConnection->connect()
#1 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): SiteConfigController->actionTestConnection()
#2 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\work\framework\web\CController.php(287): SiteConfigController->runAction()
#4 C:\xampp\htdocs\work\framework\web\CController.php(266): SiteConfigController->runActionWithFilters()
#5 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): SiteConfigController->run()
#6 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#7 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#8 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/siteconfig/testConnection?SiteConfig[code]=0001&SiteConfig[name]=Battambong&SiteConfig[host]=localhost&SiteConfig[db]=site_new_oi&SiteConfig[user]=saj&SiteConfig[password]=123456&_=1331884216094
in C:\xampp\htdocs\work\data-aggregration\protected\models\DaDbConnection.php (22)
in C:\xampp\htdocs\work\data-aggregration\protected\models\DaDbConnection.php (11)
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\SiteConfigController.php (76)
2012/03/16 10:29:59 [error] [php] Use of undefined constant sqlsrv_errors - assumed 'sqlsrv_errors' (C:\xampp\htdocs\work\data-aggregration\protected\models\DaDbConnection.php:22)
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): SiteConfigController->actionTestConnection()
#1 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams()
#2 C:\xampp\htdocs\work\framework\web\CController.php(287): SiteConfigController->runAction()
#3 C:\xampp\htdocs\work\framework\web\CController.php(266): SiteConfigController->runActionWithFilters()
#4 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): SiteConfigController->run()
#5 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#6 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#7 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/work/data-aggregration/index.php/siteconfig/testConnection?SiteConfig%5Bcode%5D=0001&SiteConfig%5Bname%5D=Battambong&SiteConfig%5Bhost%5D=localhost&SiteConfig%5Bdb%5D=site_new_oi&SiteConfig%5Buser%5D=sas&SiteConfig%5Bpassword%5D=123456&_=1331890198741
in C:\xampp\htdocs\work\data-aggregration\protected\models\DaDbConnection.php (22)
in C:\xampp\htdocs\work\data-aggregration\protected\models\DaDbConnection.php (11)
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\SiteConfigController.php (76)
2012/03/17 01:00:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/17 01:05:04 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/17 01:10:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/17 01:15:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/17 01:20:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/17 01:25:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/17 01:30:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/17 01:35:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/17 01:40:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/17 01:45:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/17 01:50:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/17 01:55:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/17 02:00:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/17 02:05:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/17 02:10:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/17 02:15:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/17 02:20:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/17 02:25:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/17 02:30:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/18 05:48:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/18 05:49:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/18 05:49:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/18 05:53:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/18 06:06:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/18 06:07:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/18 06:12:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/18 06:59:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/19 02:15:02 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/19 02:20:02 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/19 02:25:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/19 02:30:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/19 02:35:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/19 02:40:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/19 02:45:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/19 02:50:01 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/19 04:35:02 [error] [php] PDO::__construct(): [2002] No connection could be made because the target machine actively refused it.
 (trying to connect via tcp://localhost:3306) (C:\xampp\htdocs\work\framework\db\CDbConnection.php:422)
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 C:\xampp\htdocs\work\framework\db\CDbConnection.php(309): CDbConnection->setActive()
#2 C:\xampp\htdocs\work\framework\base\CModule.php(388): CDbConnection->init()
#3 C:\xampp\htdocs\work\framework\base\CModule.php(104): CConsoleApplication->getComponent()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php(5): CConsoleApplication->__get()
#5 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(15): require_once()

in C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJobConfig.php (5)
in C:\xampp\htdocs\work\data-aggregration\jobrunner.php (15)
2012/03/19 04:39:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/19 04:39:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/19 04:41:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/19 04:41:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/19 04:42:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/19 04:43:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/19 04:44:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/19 04:44:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/19 04:44:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/19 04:44:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/19 04:53:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/19 05:21:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/19 05:22:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/19 05:22:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/19 05:30:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/19 05:42:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/19 05:44:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/19 06:52:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/19 06:59:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/19 08:10:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/03/21 03:40:22 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`server_oi_test`.`tblavlostdead`, CONSTRAINT `FK_tblAVLostDead_tblAVmain` FOREIGN KEY (`AV_ID`, `ID`) REFERENCES `tblavmain` (`AV_ID`, `ID`) ON DELETE NO ACTION ON UPDATE NO ACTION). The SQL statement executed was: REPLACE INTO tblavlostdead (clinicid,  status,  lddate,  av_id,  id) VALUES (:clinicid, :status, :lddate, :av_id, :id).
2012/03/21 04:17:03 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'server_oi_test.da_site_configs' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `da_site_configs`.
2012/03/21 04:17:03 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'group_id' cannot be null. The SQL statement executed was: INSERT INTO `da_users` (`name`, `login`, `password`, `group_id`, `email`, `active`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
2012/03/21 04:18:47 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'server_oi_test.da_site_configs' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `da_site_configs`.
2012/03/21 04:18:47 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'group_id' cannot be null. The SQL statement executed was: INSERT INTO `da_users` (`name`, `login`, `password`, `group_id`, `email`, `active`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
2012/03/21 04:19:20 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'server_oi_test.da_site_configs' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `da_site_configs`.
2012/03/21 04:19:20 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'group_id' cannot be null. The SQL statement executed was: INSERT INTO `da_users` (`name`, `login`, `password`, `group_id`, `email`, `active`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
2012/03/21 05:34:02 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.av_id tblavlostdead as L2  GROUP BY av_id' at line 1. The SQL statement executed was:  SELECT * from tblavlostdead as L1   INNER JOIN L1.av_id = L2.av_id tblavlostdead as L2  GROUP BY av_id .
2012/03/21 05:35:09 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.av_id tblavlostdead as L2  GROUP BY L1.av_id' at line 1. The SQL statement executed was:  SELECT * from tblavlostdead as L1   INNER JOIN L1.av_id = L2.av_id tblavlostdead as L2  GROUP BY L1.av_id .
2012/03/21 06:01:29 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'status = 'dead'  group by clinicid , av_id, id  ORDER BY lldate desc' at line 1. The SQL statement executed was:  SELECT * from tblavlostdead as L1   status = 'dead'  group by clinicid , av_id, id  ORDER BY lldate desc .
2012/03/21 06:04:24 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'status = 'dead'  group by clinicid , av_id, id  ORDER BY lldate desc' at line 1. The SQL statement executed was:  SELECT * from tblavlostdead as L1   status = 'dead'  group by clinicid , av_id, id  ORDER BY lldate desc .
2012/03/21 08:26:44 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'lldate' in 'order clause'. The SQL statement executed was:  SELECT * from tblavlostdead as L1   WHERE status = 'dead'  group by clinicid , av_id, id  ORDER BY lldate desc .
2012/03/21 08:49:28 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'DeadFirst.lldate' in 'where clause'. The SQL statement executed was:  SELECT L2.*  from tblavlostdead as L2 INNER JOIN   ( SELECT *  from tblavlostdead as L1   WHERE status = 'dead'  group by clinicid , av_id, id  ORDER BY lddate asc ) AS DeadFirst   WHERE L2.status = 'lost'  AND L2.lddate > DeadFirst.lldate  AND L2.clinicid = DeadFirst.clinicid   AND L2.av_id = DeadFirst.av_id   AND L2.id = DeadFirst.id  .
2012/03/21 08:52:05 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'DeadFirst.lldate' in 'where clause'. The SQL statement executed was:  SELECT L2.*  from tblavlostdead as L2 INNER JOIN   ( SELECT *  from tblavlostdead as L1   WHERE L1.status = 'dead'  group by L1.clinicid , L1.av_id, L1.id  ORDER BY L1.lddate asc ) DeadFirst    WHERE L2.status = 'lost'  AND L2.lddate > DeadFirst.lldate  AND L2.clinicid = DeadFirst.clinicid   AND L2.av_id = DeadFirst.av_id   AND L2.id = DeadFirst.id  .
2012/03/21 09:04:06 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'DeadFirst.lldate' in 'where clause'. The SQL statement executed was:  SELECT L2.*  from 
 tblavlostdead as L2 INNER JOIN   ( SELECT *  from 
 tblavlostdead as L1  
 WHERE L1.status = 'dead' 
 group by L1.clinicid , L1.av_id, L1.id 
 ORDER BY L1.lddate asc ) DeadFirst   
 WHERE L2.status = 'lost' 
 AND L2.lddate > DeadFirst.lldate 
 AND L2.clinicid = DeadFirst.clinicid  
 AND L2.av_id = DeadFirst.av_id  
 AND L2.id = DeadFirst.id  .
2012/03/21 09:06:27 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'DeadFirst.lldate' in 'where clause'. The SQL statement executed was:  SELECT L2.*  from 
 tblavlostdead as L2 JOIN   ( SELECT *  from 
 tblavlostdead as L1  
 WHERE L1.status = 'dead' 
 group by L1.clinicid , L1.av_id, L1.id 
 ORDER BY L1.lddate asc ) DeadFirst   
 WHERE L2.status = 'lost' 
 AND L2.lddate > DeadFirst.lldate 
 AND L2.clinicid = DeadFirst.clinicid  
 AND L2.av_id = DeadFirst.av_id  
 AND L2.id = DeadFirst.id  .
2012/03/21 09:13:06 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'DeadFirst.lldate' in 'where clause'. The SQL statement executed was:  SELECT L2.*  from 
 tblavlostdead as L2 JOIN   ( SELECT L1.*  from 
 tblavlostdead as L1  
 WHERE L1.status = 'dead' 
 group by L1.clinicid , L1.av_id, L1.id 
 ORDER BY L1.lddate asc ) AS DeadFirst   
 WHERE L2.status = 'lost' 
 AND L2.lddate > DeadFirst.lldate 
 AND L2.clinicid = DeadFirst.clinicid  
 AND L2.av_id = DeadFirst.av_id  
 AND L2.id = DeadFirst.id  .
2012/03/21 09:20:22 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND T1.lddate > T2.lldate 
 AND T1.clinicid = T2.clinicid  
 AND T1.av_id = T2.a' at line 10. The SQL statement executed was:  SELECT * FROM  ( SELECT L2.*  from 
 tblavlostdead as L2  
 WHERE L2.status = 'lost' 
 group by L2.clinicid , L2.av_id, L2.id 
 ORDER BY L2.lddate desc )   AS T1 INNER JOIN  ( SELECT L1.*  from 
 tblavlostdead as L1  
 WHERE L1.status = 'dead' 
 group by L1.clinicid , L1.av_id, L1.id 
 ORDER BY L1.lddate asc )  AS T2
 AND T1.lddate > T2.lldate 
 AND T1.clinicid = T2.clinicid  
 AND T1.av_id = T2.av_id  
 AND T1.id = T2.id  .
2012/03/21 09:39:37 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '*) FROM  ( SELECT L2.*  FROM 
 tblavlostdead as L2  
 WHERE L2.status = 'lost' )' at line 1. The SQL statement executed was:  SELECT distinct(*) FROM  ( SELECT L2.*  FROM 
 tblavlostdead as L2  
 WHERE L2.status = 'lost' )   AS T1 INNER JOIN  ( SELECT L1.*  FROM 
 tblavlostdead as L1  
 WHERE L1.status = 'dead' )  AS T2
 WHERE T1.lddate > T2.lddate 
 AND T1.clinicid = T2.clinicid  
 AND T1.av_id = T2.av_id  
 AND T1.id = T2.id  .
2012/03/21 09:45:49 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[21000]: Cardinality violation: 1241 Operand should contain 1 column(s). The SQL statement executed was:  SELECT DISTINCT(T1.clinicid, T1.av_id, T1.id, T1.lddate)  FROM  ( SELECT L2.*  FROM 
 tblavlostdead as L2  
 WHERE L2.status = 'lost' )   AS T1 INNER JOIN  ( SELECT L1.*  FROM 
 tblavlostdead as L1  
 WHERE L1.status = 'dead' )  AS T2
 WHERE T1.lddate > T2.lddate 
 AND T1.clinicid = T2.clinicid  
 AND T1.av_id = T2.av_id  
 AND T1.id = T2.id  .
2012/03/21 09:58:20 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'L1'. The SQL statement executed was:  SELECT Lost.*, Lost.lddate as LostDate, Dead.lddate as DeadDate  FROM 
  ( SELECT L1.*  FROM tblavlostdead as L2 WHERE L2.status = 'lost' )  AS Lost INNER JOIN  ( SELECT L1.*  FROM tblavlostdead as L1 WHERE L1.status = 'dead' )  AS Dead 
 WHERE Lost.lddate > Dead.lddate 
 AND Lost.clinicid = Dead.clinicid  
 AND Lost.av_id = Dead.av_id  
 AND Lost.id = Dead.id  
 GROUP BY Lost.clinicid, Lost.av_id, Lost.id .
2012/03/22 08:09:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "rejectconditions/index".' in C:\xampp\htdocs\work\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('rejectcondition...')
#1 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/work/data-aggregration/index.php/rejectconditions/index?import_site_history=20
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=2
---
2012/03/22 08:09:54 [error] [php] Undefined index: import_site_history_id (C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectConditionController.php:9)
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CController.php(287): RejectConditionController->runAction()
#1 C:\xampp\htdocs\work\framework\web\CController.php(266): RejectConditionController->runActionWithFilters()
#2 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): RejectConditionController->run()
#3 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/work/data-aggregration/index.php/rejectcondition/index?import_site_history=20
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectConditionController.php (9)
in C:\xampp\htdocs\work\data-aggregration\index.php (13)
2012/03/22 08:10:55 [error] [php] Undefined index: import_site_history_id (C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectConditionController.php:9)
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CController.php(287): RejectConditionController->runAction()
#1 C:\xampp\htdocs\work\framework\web\CController.php(266): RejectConditionController->runActionWithFilters()
#2 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): RejectConditionController->run()
#3 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/work/data-aggregration/index.php/rejectcondition/index?import_site_history=20
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectConditionController.php (9)
in C:\xampp\htdocs\work\data-aggregration\index.php (13)
2012/03/22 08:10:58 [error] [php] Undefined index: import_site_history_id (C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectConditionController.php:9)
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CController.php(287): RejectConditionController->runAction()
#1 C:\xampp\htdocs\work\framework\web\CController.php(266): RejectConditionController->runActionWithFilters()
#2 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): RejectConditionController->run()
#3 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/work/data-aggregration/index.php/rejectcondition/index?import_site_history=20
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectConditionController.php (9)
in C:\xampp\htdocs\work\data-aggregration\index.php (13)
2012/03/22 08:11:00 [error] [php] Undefined index: import_site_history_id (C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectConditionController.php:9)
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CController.php(287): RejectConditionController->runAction()
#1 C:\xampp\htdocs\work\framework\web\CController.php(266): RejectConditionController->runActionWithFilters()
#2 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): RejectConditionController->run()
#3 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/work/data-aggregration/index.php/rejectcondition/index?import_site_history=20
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectConditionController.php (9)
in C:\xampp\htdocs\work\data-aggregration\index.php (13)
2012/03/22 08:11:33 [error] [php] Undefined index: import_site_history_id (C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectConditionController.php:9)
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CController.php(287): RejectConditionController->runAction()
#1 C:\xampp\htdocs\work\framework\web\CController.php(266): RejectConditionController->runActionWithFilters()
#2 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): RejectConditionController->run()
#3 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/work/data-aggregration/index.php/rejectcondition/index?import_site_history=20
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectConditionController.php (9)
in C:\xampp\htdocs\work\data-aggregration\index.php (13)
2012/03/22 10:07:39 [error] [exception.CException] exception 'CException' with message 'Property "RejectCondition.table" is not defined.' in C:\xampp\htdocs\work\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\ar\CActiveRecord.php(144): CComponent->__get('table')
#1 C:\xampp\htdocs\work\data-aggregration\protected\views\rejectCondition\index.php(24): CActiveRecord->__get('table')
#2 C:\xampp\htdocs\work\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\work\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\work\framework\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\work\framework\web\CController.php(783): CController->renderPartial('index', Array, true)
#6 C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectConditionController.php(20): CController->render('index', Array)
#7 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): RejectConditionController->actionIndex()
#8 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\work\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\work\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): CController->run('index')
#12 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('rejectcondition...')
#13 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/work/data-aggregration/index.php/rejectcondition/index?import_site_history_id=31
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=2
---
2012/03/22 10:58:19 [error] [php] Undefined variable: var (C:\xampp\htdocs\work\data-aggregration\protected\views\rejectCondition\index.php:34)
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CController.php(870): RejectConditionController->renderFile()
#1 C:\xampp\htdocs\work\framework\web\CController.php(783): RejectConditionController->renderPartial()
#2 C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectConditionController.php(20): RejectConditionController->render()
#3 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): RejectConditionController->actionIndex()
#4 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\work\framework\web\CController.php(287): RejectConditionController->runAction()
#6 C:\xampp\htdocs\work\framework\web\CController.php(266): RejectConditionController->runActionWithFilters()
#7 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): RejectConditionController->run()
#8 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#9 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/work/data-aggregration/index.php/rejectcondition/index?import_site_history_id=31
in C:\xampp\htdocs\work\data-aggregration\protected\views\rejectCondition\index.php (34)
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectConditionController.php (20)
in C:\xampp\htdocs\work\data-aggregration\index.php (13)
2012/03/22 11:37:37 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`server_oi_dev`.`da_reject_conditions`, CONSTRAINT `fk_da_reject_conditions_import_site_history_id` FOREIGN KEY (`import_site_history_id`) REFERENCES `da_import_site_histories` (`id`)). The SQL statement executed was: DELETE FROM `da_import_site_histories` WHERE `da_import_site_histories`.`id`=31.
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php (33)
in C:\xampp\htdocs\work\data-aggregration\index.php (13)
2012/03/22 11:37:37 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`server_oi_dev`.`da_reject_conditions`, CONSTRAINT `fk_da_reject_conditions_import_site_history_id` FOREIGN KEY (`import_site_history_id`) REFERENCES `da_import_site_histories` (`id`)). The SQL statement executed was: DELETE FROM `da_import_site_histories` WHERE `da_import_site_histories`.`id`=31' in C:\xampp\htdocs\work\framework\db\CDbCommand.php:354
Stack trace:
#0 C:\xampp\htdocs\work\framework\db\ar\CActiveRecord.php(1735): CDbCommand->execute()
#1 C:\xampp\htdocs\work\framework\db\ar\CActiveRecord.php(1159): CActiveRecord->deleteByPk('31')
#2 C:\xampp\htdocs\work\data-aggregration\protected\controllers\ImportSiteHistoryController.php(33): CActiveRecord->delete()
#3 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): ImportSiteHistoryController->actionDelete()
#4 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\work\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\work\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): CController->run('delete')
#8 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('importsitehisto...')
#9 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/work/data-aggregration/index.php/importsitehistory/delete/31
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=2
---
2012/04/03 04:25:34 [error] [php] Undefined property: DaImportSequence::$dbx (C:\xampp\htdocs\work\data-aggregration\protected\components\DaImportSequence.php:269)
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\protected\components\DaImportSequence.php(177): DaImportSequence->importIMainChildrenPartial()
#1 C:\xampp\htdocs\work\data-aggregration\protected\components\DaImportSequence.php(209): DaImportSequence->importIMain()
#2 C:\xampp\htdocs\work\data-aggregration\protected\components\DaImportSequence.php(113): DaImportSequence->importAiMain()
#3 C:\xampp\htdocs\work\data-aggregration\protected\components\DaImportSiteJob.php(11): DaImportSequence->start()
#4 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJob.php(244): DaImportSiteJob->perform()
#5 C:\xampp\htdocs\work\data-aggregration\protected\vendors\djjob\DJJob.php(212): DJJob->run()
#6 C:\xampp\htdocs\work\data-aggregration\jobrunner.php(21): DJWorker->start()

in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImportSequence.php (269)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImportSequence.php (261)
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaImportSequence.php (251)
2012/04/03 05:48:30 [error] [php] Undefined variable: message (C:\xampp\htdocs\work\data-aggregration\protected\views\rejectPatient\index.php:27)
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CController.php(870): RejectPatientController->renderFile()
#1 C:\xampp\htdocs\work\framework\web\CController.php(783): RejectPatientController->renderPartial()
#2 C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectPatientController.php(20): RejectPatientController->render()
#3 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): RejectPatientController->actionIndex()
#4 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\work\framework\web\CController.php(287): RejectPatientController->runAction()
#6 C:\xampp\htdocs\work\framework\web\CController.php(266): RejectPatientController->runActionWithFilters()
#7 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): RejectPatientController->run()
#8 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#9 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/work/data-aggregration/index.php/rejectpatient/index?import_site_history_id=48
in C:\xampp\htdocs\work\data-aggregration\protected\views\rejectPatient\index.php (27)
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectPatientController.php (20)
in C:\xampp\htdocs\work\data-aggregration\index.php (13)
2012/04/03 05:49:12 [error] [php] htmlentities() expects parameter 1 to be string, array given (C:\xampp\htdocs\work\data-aggregration\protected\views\rejectPatient\index.php:43)
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CBaseController.php(96): RejectPatientController->renderInternal()
#1 C:\xampp\htdocs\work\framework\web\CController.php(870): RejectPatientController->renderFile()
#2 C:\xampp\htdocs\work\framework\web\CController.php(783): RejectPatientController->renderPartial()
#3 C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectPatientController.php(20): RejectPatientController->render()
#4 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): RejectPatientController->actionIndex()
#5 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams()
#6 C:\xampp\htdocs\work\framework\web\CController.php(287): RejectPatientController->runAction()
#7 C:\xampp\htdocs\work\framework\web\CController.php(266): RejectPatientController->runActionWithFilters()
#8 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): RejectPatientController->run()
#9 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#10 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#11 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/work/data-aggregration/index.php/rejectpatient/index?import_site_history_id=48
in C:\xampp\htdocs\work\data-aggregration\protected\views\rejectPatient\index.php (43)
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectPatientController.php (20)
in C:\xampp\htdocs\work\data-aggregration\index.php (13)
2012/04/03 09:01:34 [error] [exception.CException] exception 'CException' with message 'Property "RejectPatientController.err_records" is not defined.' in C:\xampp\htdocs\work\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\protected\views\rejectPatient\index.php(53): CComponent->__get('err_records')
#1 C:\xampp\htdocs\work\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#2 C:\xampp\htdocs\work\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#3 C:\xampp\htdocs\work\framework\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\work\framework\web\CController.php(783): CController->renderPartial('index', Array, true)
#5 C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectPatientController.php(20): CController->render('index', Array)
#6 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): RejectPatientController->actionIndex()
#7 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\work\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\work\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): CController->run('index')
#11 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('rejectpatient/i...')
#12 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#13 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/work/data-aggregration/index.php/rejectpatient/index?import_site_history_id=48
HTTP_REFERER=http://localhost/work/data-aggregration/index.php/importsitehistory/index?siteconfig_id=2
---
2012/04/03 09:04:19 [error] [exception.CException] exception 'CException' with message 'Property "RejectPatientController.err_records" is not defined.' in C:\xampp\htdocs\work\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\work\data-aggregration\protected\views\rejectPatient\index.php(53): CComponent->__get('err_records')
#1 C:\xampp\htdocs\work\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#2 C:\xampp\htdocs\work\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#3 C:\xampp\htdocs\work\framework\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\work\framework\web\CController.php(783): CController->renderPartial('index', Array, true)
#5 C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectPatientController.php(20): CController->render('index', Array)
#6 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): RejectPatientController->actionIndex()
#7 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\work\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\work\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): CController->run('index')
#11 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController('rejectpatient/i...')
#12 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#13 C:\xampp\htdocs\work\data-aggregration\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/work/data-aggregration/index.php/rejectpatient/index?import_site_history_id=48
---
2012/04/03 09:05:08 [error] [php] unserialize() [<a href='function.unserialize'>function.unserialize</a>]: Error at offset 65532 of 65535 bytes (C:\xampp\htdocs\work\data-aggregration\protected\views\rejectPatient\index.php:53)
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CBaseController.php(96): RejectPatientController->renderInternal()
#1 C:\xampp\htdocs\work\framework\web\CController.php(870): RejectPatientController->renderFile()
#2 C:\xampp\htdocs\work\framework\web\CController.php(783): RejectPatientController->renderPartial()
#3 C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectPatientController.php(20): RejectPatientController->render()
#4 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): RejectPatientController->actionIndex()
#5 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams()
#6 C:\xampp\htdocs\work\framework\web\CController.php(287): RejectPatientController->runAction()
#7 C:\xampp\htdocs\work\framework\web\CController.php(266): RejectPatientController->runActionWithFilters()
#8 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): RejectPatientController->run()
#9 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#10 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#11 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/work/data-aggregration/index.php/rejectpatient/index?import_site_history_id=48
in C:\xampp\htdocs\work\data-aggregration\protected\views\rejectPatient\index.php (53)
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectPatientController.php (20)
in C:\xampp\htdocs\work\data-aggregration\index.php (13)
2012/04/03 09:17:13 [error] [php] unserialize() [<a href='function.unserialize'>function.unserialize</a>]: Error at offset 65532 of 65535 bytes (C:\xampp\htdocs\work\data-aggregration\protected\views\rejectPatient\index.php:53)
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CBaseController.php(96): RejectPatientController->renderInternal()
#1 C:\xampp\htdocs\work\framework\web\CController.php(870): RejectPatientController->renderFile()
#2 C:\xampp\htdocs\work\framework\web\CController.php(783): RejectPatientController->renderPartial()
#3 C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectPatientController.php(20): RejectPatientController->render()
#4 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): RejectPatientController->actionIndex()
#5 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams()
#6 C:\xampp\htdocs\work\framework\web\CController.php(287): RejectPatientController->runAction()
#7 C:\xampp\htdocs\work\framework\web\CController.php(266): RejectPatientController->runActionWithFilters()
#8 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): RejectPatientController->run()
#9 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#10 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#11 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/work/data-aggregration/index.php/rejectpatient/index?import_site_history_id=1&page=10
in C:\xampp\htdocs\work\data-aggregration\protected\views\rejectPatient\index.php (53)
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectPatientController.php (20)
in C:\xampp\htdocs\work\data-aggregration\index.php (13)
2012/04/03 09:28:24 [error] [php] Undefined variable: records (C:\xampp\htdocs\work\data-aggregration\protected\components\DaViewHelper.php:74)
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CBaseController.php(96): RejectPatientController->renderInternal()
#1 C:\xampp\htdocs\work\framework\web\CController.php(870): RejectPatientController->renderFile()
#2 C:\xampp\htdocs\work\framework\web\CController.php(783): RejectPatientController->renderPartial()
#3 C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectPatientController.php(20): RejectPatientController->render()
#4 C:\xampp\htdocs\work\framework\web\actions\CInlineAction.php(50): RejectPatientController->actionIndex()
#5 C:\xampp\htdocs\work\framework\web\CController.php(309): CInlineAction->runWithParams()
#6 C:\xampp\htdocs\work\framework\web\CController.php(287): RejectPatientController->runAction()
#7 C:\xampp\htdocs\work\framework\web\CController.php(266): RejectPatientController->runActionWithFilters()
#8 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): RejectPatientController->run()
#9 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#10 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#11 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/work/data-aggregration/index.php/rejectpatient/index?import_site_history_id=1&page=10
in C:\xampp\htdocs\work\data-aggregration\protected\components\DaViewHelper.php (74)
in C:\xampp\htdocs\work\data-aggregration\protected\views\rejectPatient\index.php (55)
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectPatientController.php (20)
2012/04/03 09:29:00 [error] [php] Undefined index: import_site_history_id (C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectPatientController.php:9)
Stack trace:
#0 C:\xampp\htdocs\work\framework\web\CController.php(287): RejectPatientController->runAction()
#1 C:\xampp\htdocs\work\framework\web\CController.php(266): RejectPatientController->runActionWithFilters()
#2 C:\xampp\htdocs\work\framework\web\CWebApplication.php(276): RejectPatientController->run()
#3 C:\xampp\htdocs\work\framework\web\CWebApplication.php(135): CWebApplication->runController()
#4 C:\xampp\htdocs\work\framework\base\CApplication.php(162): CWebApplication->processRequest()
#5 C:\xampp\htdocs\work\data-aggregration\index.php(13): CWebApplication->run()
REQUEST_URI=/work/data-aggregration/index.php/rejectpatient/index
in C:\xampp\htdocs\work\data-aggregration\protected\controllers\RejectPatientController.php (9)
in C:\xampp\htdocs\work\data-aggregration\index.php (13)
